import type { AssetClass } from "./market";
import type { Locale } from "./i18n/locale";
import { assetClassContent } from "./asset-classes";

const translated: Record<Exclude<Locale, "en">, Record<AssetClass, {
  tagline: string; lead: string; statLabel: string;
  highlights: { title: string; body: string }[]; drivers: string[];
}>> = {
  fr: {
    forex: { tagline: "Paires majeures, mineures et exotiques avec la liquidité des banques de premier rang.", lead: "Le plus grand marché du monde, coté en continu de l’ouverture de Sydney à la clôture de New York. Négociez les paires majeures dès 0,0 pip avec les mêmes conditions pendant la séance de Londres comme à 3 h du matin.", statLabel: "pips à partir de", highlights: [{ title: "Prix interbancaires bruts", body: "Les cours agrègent la liquidité de banques et teneurs de marché de premier rang, sans majoration de spread par un desk." }, { title: "Aucun élargissement imposé", body: "Les spreads ne sont pas élargis administrativement lors des annonces prévues. Si la liquidité baisse, le carnet le reflète." }, { title: "Séances étendues", body: "Cours continus pendant les séances asiatiques, européennes et américaines, avec les spreads les plus serrés lors des chevauchements." }], drivers: ["Décisions des banques centrales et trajectoire des taux intégrée aux marchés à terme", "Inflation, emploi et PIB des deux économies de la paire", "Sentiment du risque, qui soutient généralement le dollar, le yen et le franc suisse lors des replis", "Flux transfrontaliers en fin de mois et fixing de Londres à 16 h"] },
    metals: { tagline: "Or, argent, platine et palladium sur les principaux marchés au comptant.", lead: "Les métaux précieux se situent entre devises et matières premières, et se comportent comme les deux. L’or et l’argent suivent les marchés au comptant utilisés par les professionnels, sans échéance ni report de contrat à terme.", statLabel: "spread XAU typique", highlights: [{ title: "Marché au comptant", body: "Les métaux sont cotés en CFD au comptant : aucun contrat n’arrive à échéance et aucun écart calendaire n’est intégré à votre position." }, { title: "Couverture de portefeuille", body: "L’or a historiquement présenté une corrélation faible ou négative avec les indices actions, ce qui explique son attrait lorsque les actifs risqués reculent." }, { title: "Liquidité réelle en séance asiatique", body: "La liquidité se maintient pendant la séance asiatique au lieu de se limiter à un cours symbolique." }], drivers: ["Rendements réels : l’or ne verse pas de coupon et concurrence directement les taux corrigés de l’inflation", "Force du dollar, les métaux étant libellés en dollars dans le monde entier", "Achats des banques centrales, moteur structurel majeur de la demande", "Demande industrielle, déterminante pour l’argent, le platine et le palladium"] },
    indices: { tagline: "Négociez l’UT100-20 (Nasdaq 100) et les grands indices mondiaux.", lead: "Négociez l’UT100-20 (Nasdaq 100) et les indices qui orientent le sentiment de risque mondial. Une seule position donne accès à tout un indice, sans le risque lié aux résultats d’une société particulière.", statLabel: "spread SPX500 typique", highlights: [{ title: "Indices cash, pas contrats à terme", body: "Les cours des indices cash suivent directement l’indice de référence, sans écart avec le contrat à terme proche ni renouvellement trimestriel." }, { title: "Presque toute la journée", body: "Les indices américains sont cotés 23 heures par jour : les nouvelles nocturnes peuvent être négociées sans attendre la réouverture." }, { title: "Diversification intégrée", body: "Une position sur un indice répartit le risque entre ses composants et se comporte différemment d’un CFD sur action." }], drivers: ["Anticipations de taux, qui réévaluent les actions avant que les résultats ne changent", "Saison des résultats, où quelques grandes capitalisations dominent les indices américains", "Rotation sectorielle entre croissance et valeur au fil du cycle", "Risque géopolitique, qui touche souvent d’abord les indices européens et asiatiques"] },
    commodities: { tagline: "WTI, Brent et gaz naturel avec des cours compétitifs en continu.", lead: "L’énergie est le marché le plus sensible aux actualités. Le WTI, le Brent et le gaz naturel sont cotés en continu : les stocks et annonces de l’OPEP+ peuvent être négociés dès leur publication.", statLabel: "spread WTI typique", highlights: [{ title: "Les deux références pétrolières", body: "Le WTI et le Brent sont cotés côte à côte, ce qui permet de prendre directement position sur leur écart." }, { title: "Un marché rythmé par les annonces", body: "Les stocks hebdomadaires et les décisions de l’OPEP+ font évoluer le marché en quelques secondes ; les cours restent actifs." }, { title: "Exposition directe à l’inflation", body: "L’énergie influe directement sur l’inflation globale et constitue une couverture macroéconomique concrète." }], drivers: ["Quotas de production de l’OPEP+ et respect de ces quotas", "Rapports hebdomadaires américains sur les stocks de pétrole brut et de gaz naturel", "Perturbations de l’offre liées aux conflits, sanctions ou conditions météo", "Perspectives de croissance mondiale, qui déterminent la demande"] },
    crypto: { tagline: "Bitcoin, Ethereum et Solana cotés aussi le week-end.", lead: "Les CFD sur actifs numériques permettent de prendre une position acheteuse ou vendeuse sans portefeuille ni retrait sur une plateforme d’échange. Les cours sont disponibles 24 h/24, y compris le week-end.", statLabel: "week-ends inclus", highlights: [{ title: "Aucun risque de conservation", body: "Vous négociez le prix : aucun portefeuille à sécuriser, aucune phrase de récupération à perdre et aucun solde d’échange à retirer." }, { title: "Acheter ou vendre", body: "Le CFD est symétrique : exprimer une opinion baissière se fait avec le même ticket qu’une position haussière, sans emprunt." }, { title: "Cours le week-end", body: "Les cryptomonnaies sont la seule classe cotée ici le samedi et le dimanche, périodes où elles évoluent souvent." }], drivers: ["Conditions mondiales de liquidité, que les cryptomonnaies suivent étroitement", "Décisions réglementaires et flux des ETF au comptant dans les principaux marchés", "Événements réseau : réductions de moitié, mises à niveau et migrations majeures", "Accumulation de levier, qui peut transformer des mouvements ordinaires en liquidations en cascade"] },
    stocks: { tagline: "CFD sur les grandes actions américaines les plus échangées.", lead: "Négociez les sociétés individuelles qui influencent les indices. Les CFD sur actions suivent la cotation principale pendant la séance américaine régulière, avec un levier jusqu’à 1:100.", statLabel: "levier max.", highlights: [{ title: "Tailles fractionnées", body: "La taille se définit en lots plutôt qu’en actions entières ; un titre à plusieurs milliers de dollars ne nécessite donc pas un ticket équivalent." }, { title: "Positions acheteuses ou vendeuses", body: "Les positions vendeuses ne nécessitent pas d’emprunter des actions et ne présentent pas de risque de rappel." }, { title: "Cours de la place principale", body: "Les cours suivent la place de cotation principale pendant les heures normales, plutôt qu’une cotation secondaire peu liquide." }], drivers: ["Résultats trimestriels et indications prospectives des entreprises", "Flux sectoriels et indiciels, qui influencent les composants indépendamment de leurs actualités", "Révisions des analystes et positionnements qui les anticipent", "Anticipations de taux, particulièrement importantes pour les valeurs de croissance à long terme"] },
  },
  ar: {
    forex: { tagline: "أزواج رئيسية وثانوية ونادرة بسيولة من بنوك رائدة.", lead: "أكبر سوق في العالم، بأسعار مستمرة من افتتاح سيدني إلى إغلاق نيويورك. تداول الأزواج الرئيسية ابتداءً من 0.0 نقطة وبالتسعير نفسه خلال جلسة لندن وفي ساعات التداول الهادئة.", statLabel: "نقطة ابتداءً من", highlights: [{ title: "تسعير خام بين البنوك", body: "تُجمع الأسعار من سيولة بنوك وصناع سوق رائدين، وتُعرض دون زيادة على السبريد من مكتب التداول." }, { title: "لا توسيع مفروض", body: "لا نوسّع السبريد إداريًا عند الإصدارات المجدولة. وإذا انخفضت السيولة، يظهر ذلك في دفتر الأسعار." }, { title: "تغطية جلسات ممتدة", body: "أسعار مستمرة خلال الجلسات الآسيوية والأوروبية والأمريكية، مع أضيق فروق الأسعار عند تداخل الجلسات." }], drivers: ["قرارات البنوك المركزية ومسار أسعار الفائدة الذي تعكسه العقود الآجلة", "بيانات التضخم والتوظيف والناتج المحلي للاقتصادين في الزوج", "معنويات المخاطر التي تدعم عادةً الدولار والين والفرنك عند تراجع الأسواق", "التدفقات العابرة للحدود في نهاية الشهر وسعر تثبيت لندن عند الرابعة"] },
    metals: { tagline: "الذهب والفضة والبلاتين والبلاديوم وفق أسعار الأسواق الفورية الرئيسية.", lead: "تقع المعادن الثمينة بين العملات والسلع وتجمع خصائصهما. يتبع الذهب والفضة أسواق التداول الفوري، دون تاريخ انتهاء للعقد أو ترحيل للعقود الآجلة.", statLabel: "سبريد XAU المعتاد", highlights: [{ title: "تداول فوري لا عقود آجلة", body: "تُسعّر المعادن كعقود فروقات فورية، فلا يوجد تاريخ انتهاء للعقد ولا فروق آجلة تُضاف إلى مركزك." }, { title: "تحوط للمحفظة", body: "ارتبط الذهب تاريخيًا ارتباطًا منخفضًا أو سلبيًا بمؤشرات الأسهم، لذا قد يرتفع عندما تتراجع الأصول عالية المخاطر." }, { title: "سيولة حقيقية على مدار الجلسات", body: "تستمر السيولة خلال الجلسة الآسيوية بدلًا من الاكتفاء بسعر رمزي." }], drivers: ["العوائد الحقيقية؛ فالذهب لا يدر عائدًا وينافس أسعار الفائدة المعدلة حسب التضخم", "قوة الدولار لأن المعادن تُسعّر عالميًا بالدولار", "مشتريات البنوك المركزية، وهي من أهم مصادر الطلب الهيكلي", "الطلب الصناعي الذي يؤثر في الفضة والبلاتين والبلاديوم أكثر من الذهب"] },
    indices: { tagline: "تداول UT100-20 (ناسداك 100) إلى جانب المؤشرات العالمية الرئيسية.", lead: "تداول UT100-20 (ناسداك 100) والمؤشرات التي تحدد معنويات المخاطر العالمية. تمنحك صفقة واحدة تعرضًا لمؤشر كامل دون مخاطر نتائج شركة منفردة.", statLabel: "سبريد SPX500 المعتاد", highlights: [{ title: "مؤشرات نقدية لا آجلة", body: "تتبع أسعار المؤشرات النقدية المؤشر الأساسي مباشرةً دون فرق مع العقد الآجل القريب أو ترحيل ربع سنوي." }, { title: "تداول معظم ساعات اليوم", body: "تُسعّر المؤشرات الأمريكية 23 ساعة يوميًا، ما يتيح التداول على الأخبار الليلية بدلًا من مواجهة فجوة سعرية عند الافتتاح." }, { title: "تنويع مدمج", body: "توزع صفقة المؤشر المخاطر على جميع مكوناته، لذلك يختلف سلوكها عن عقد فروقات سهم واحد." }], drivers: ["توقعات أسعار الفائدة التي تعيد تقييم الأسهم قبل تغير الأرباح", "موسم الأرباح، حيث تهيمن شركات كبرى قليلة على المؤشرات الأمريكية", "التناوب بين قطاعات النمو والقيمة مع تغير الدورة الاقتصادية", "المخاطر الجيوسياسية التي تؤثر أولًا في المؤشرات الأوروبية والآسيوية"] },
    commodities: { tagline: "خام غرب تكساس وبرنت والغاز الطبيعي بأسعار تنافسية مستمرة.", lead: "الطاقة من أكثر الأسواق تأثرًا بالأخبار. تتوفر أسعار خام غرب تكساس وبرنت والغاز الطبيعي باستمرار، ما يتيح التداول عند صدور بيانات المخزون أو أخبار أوبك+ مباشرةً.", statLabel: "سبريد WTI المعتاد", highlights: [{ title: "مرجعا النفط الخام", body: "يتوفر خام غرب تكساس وبرنت معًا، ما يتيح التعبير مباشرةً عن الرأي في فرق السعر بينهما." }, { title: "سوق تحركه الأحداث", body: "تحرك بيانات المخزون الأسبوعية وقرارات أوبك+ السوق خلال ثوانٍ، وتبقى الأسعار متاحة أثناء ذلك." }, { title: "تعرض مباشر للتضخم", body: "تؤثر الطاقة مباشرةً في التضخم العام، ما يجعلها تحوطًا اقتصاديًا كليًا ملموسًا." }], drivers: ["حصص إنتاج أوبك+ ومدى الالتزام بها", "تقارير المخزون الأسبوعية الأمريكية للنفط الخام والغاز الطبيعي", "اضطرابات الإمداد بسبب النزاعات أو العقوبات أو الطقس", "توقعات النمو العالمي التي تحدد جانب الطلب"] },
    crypto: { tagline: "بيتكوين وإيثيريوم وسولانا، مع تسعير خلال عطلة نهاية الأسبوع.", lead: "تتيح عقود فروقات الأصول الرقمية فتح مراكز شراء أو بيع دون محفظة أو حدود سحب من منصة تداول. تستمر الأسعار على مدار الساعة طوال أيام الأسبوع.", statLabel: "بما في ذلك عطلات نهاية الأسبوع", highlights: [{ title: "دون مخاطر حفظ الأصول", body: "تتداول السعر فقط؛ فلا محفظة تحتاج إلى تأمين ولا عبارة استرداد قد تفقدها ولا رصيد منصة لسحبه." }, { title: "البيع والشراء بسهولة", body: "عقد الفروقات متماثل؛ فتأخذ مركزًا هابطًا عبر التذكرة نفسها للمركز الصاعد دون اقتراض." }, { title: "تغطية نهاية الأسبوع", body: "هذه الفئة الوحيدة المتاحة يومي السبت والأحد، وهما الوقت الذي تشهد فيه تحركات كثيرة." }], drivers: ["ظروف السيولة العالمية التي ترتبط بها العملات الرقمية عن كثب", "القرارات التنظيمية وتدفقات صناديق ETF الفورية في الأسواق الرئيسية", "أحداث الشبكة مثل التنصيف والترقيات وانتقالات البروتوكولات الكبرى", "تراكم الرافعة المالية الذي قد يحول التحركات العادية إلى تصفيات متتالية"] },
    stocks: { tagline: "عقود فروقات على أكثر الأسهم الأمريكية الكبرى تداولًا.", lead: "تداول الشركات الفردية التي تحرك المؤشرات. تتبع عقود فروقات الأسهم سعر الإدراج الأساسي خلال ساعات التداول الأمريكية، برافعة مالية تصل إلى 1:100.", statLabel: "أقصى رافعة مالية", highlights: [{ title: "أحجام جزئية افتراضيًا", body: "يُحدد حجم المركز باللوت لا بعدد صحيح من الأسهم، لذلك لا يفرض السهم مرتفع السعر صفقة بالقيمة نفسها." }, { title: "مراكز شراء أو بيع", body: "لا تتطلب المراكز الهابطة اقتراض الأسهم ولا تنطوي على خطر استردادها." }, { title: "تسعير السوق الأساسي", body: "تعتمد الأسعار على بورصة الإدراج الأساسية خلال ساعاتها المعتادة، لا على تداول ثانوي ضعيف السيولة." }], drivers: ["الأرباح الفصلية والتوجيهات المستقبلية للشركات", "تدفقات القطاعات والمؤشرات التي تحرك الشركات بصرف النظر عن أخبارها", "تعديلات المحللين ومراكز المستثمرين التي تسبقها", "توقعات الفائدة، ولا سيما تأثيرها في أسهم النمو طويلة الأجل"] },
  },
};

export function localizedAssetClass(locale: Locale, asset: AssetClass) {
  const base = assetClassContent[asset];
  if (locale === "en") return base;
  return { ...base, ...translated[locale][asset] };
}
