/**
 * Country list used by registration and the CRM. Restricted markets are
 * excluded at the application layer rather than hidden in the UI, so the list
 * below is the set Connect Funded can onboard today.
 */
export const countries = [
  "Andorra",
  "Argentina",
  "Australia",
  "Austria",
  "Bahrain",
  "Bangladesh",
  "Belgium",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatia",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Estonia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hong Kong SAR",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lebanon",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Rwanda",
  "San Marino",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Türkiye",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Vietnam",
  "Zambia",
] as const;

export type Country = (typeof countries)[number];

export const experienceOptions = [
  {
    value: "none",
    label: "No live trading yet",
    hint: "Demo or paper trading only",
  },
  {
    value: "under_1y",
    label: "Less than 1 year",
    hint: "Live capital, still building a process",
  },
  { value: "1_3y", label: "1 to 3 years", hint: "A tested, repeatable strategy" },
  { value: "3_5y", label: "3 to 5 years", hint: "Consistent multi-market execution" },
  {
    value: "over_5y",
    label: "More than 5 years",
    hint: "Professional or institutional background",
  },
] as const;

export type ExperienceValue = (typeof experienceOptions)[number]["value"];
