import type { Course, CourseLevel, LearningPathStage, GlossaryTerm } from "@/lib/education-content";

type CourseText = Pick<Course, "title" | "summary" | "modules">;
type PathText = Pick<LearningPathStage, "title" | "why" | "outcome">;

const frCourses: Record<string, CourseText> = {
  "market-mechanics": { title: "Mécanismes de marché et types d’ordres", summary: "Comprendre ce qu’est réellement un CFD, comment son prix est établi et quel ordre transmet l’instruction souhaitée.", modules: ["Prix d’un CFD et exposition associée", "Bid, ask, cours moyen et coût réel du spread", "Comparaison des ordres au marché, à cours limité, stop et stop-limite", "Lire la profondeur de marché sur cTrader", "Glissement de prix et écarts possibles avec le graphique", "Tailles de contrat sur le Forex, les métaux, les indices et les cryptomonnaies", "Conserver des positions la nuit et comprendre le rollover quotidien", "Passer et modifier votre premier ordre sur le Web Terminal"] },
  "pips-lots-leverage": { title: "Calcul des pips, lots et de l’effet de levier", summary: "Les calculs que tout trader sérieux effectue avant d’ouvrir une position, appliqués aux spécifications réelles des contrats.", modules: ["Pips, points et ticks : amplitude et valeur des mouvements", "Lots standard, mini et micro en pratique", "Valeur du pip sur les paires cotées en USD et sur les paires croisées", "Exposition notionnelle et marge réellement requise", "Ce que change un levier de 1:100 et ce qu’il ne change pas", "Niveau de marge, appel de marge et seuil de stop-out", "Dix exemples détaillés de dimensionnement sur quatre classes d’actifs"] },
  "session-structure": { title: "Séances, liquidité et horaires de marché", summary: "La liquidité varie au fil de la journée. Ce cours cartographie les séances en UTC et relie le choix des instruments aux horaires les plus actifs.", modules: ["Horaires de Sydney, Tokyo, Londres et New York en UTC", "Pourquoi le chevauchement Londres–New York offre la profondeur la plus importante", "Comportement du spread à l’ouverture asiatique et au rollover quotidien", "Adapter le choix des instruments à la volatilité de la séance", "Calendriers de jours fériés, séances écourtées et pièges des marchés peu liquides", "Établir un plan de séance reproductible chaque semaine"] },
  "risk-first-sizing": { title: "Dimensionner les positions en priorité selon le risque", summary: "Définissez la perte que vous acceptez, puis laissez la distance du stop déterminer la taille de la position. Une habitude essentielle pour durer.", modules: ["Risque à fraction fixe et résistance aux séries de pertes", "Convertir la distance du stop en taille de lot en trois étapes", "Dimensionner les CFD sur l’or, le pétrole et les indices sans calculateur de pips", "Table de récupération après un drawdown : pourquoi une perte de 30 % exige un gain de 42,9 %", "Corrélation : quand trois positions n’en forment réellement qu’une", "Réduire la taille avant une annonce majeure puis la réajuster après", "Créer une fiche de dimensionnement prétransaction sur une page", "Auditer le mois passé pour repérer les écarts de dimensionnement"] },
  "expectancy-and-review": { title: "Espérance, journal de trading et revue", summary: "Distinguer un mois déficitaire d’un avantage devenu inefficace, à partir de votre historique de transactions plutôt que d’une impression.", modules: ["Taux de réussite, multiple de R et avantage de l’espérance sur la précision", "Un journal qui consigne la décision, pas seulement le résultat", "Étiqueter les configurations pour écarter celles qui perdent", "Exécuter une simulation Monte-Carlo sur vos propres transactions", "Distinguer la variance normale d’un avantage qui ne fonctionne plus", "La revue mensuelle appliquée par le desk à son propre portefeuille"] },
  "structure-and-levels": { title: "Structure du marché et choix des niveaux", summary: "Tracer le graphique avec méthode et ne plus déplacer les niveaux. Un processus reproductible pour repérer les quelques prix qui comptent.", modules: ["Structure des swings : sommets et creux ascendants, et cas d’invalidation", "Tracer les niveaux une fois et éviter de les déplacer en séance", "Zones d’offre et de demande ou lignes à prix unique", "Alignement de plusieurs unités de temps sans paralysie analytique", "Volume et volume en ticks : ce que MetaTrader affiche réellement", "Placer un stop selon l’ATR plutôt qu’un chiffre rond", "Anatomie d’une fausse cassure et comment la négocier prudemment à contre-courant", "Routine de niveaux avant l’ouverture en vingt minutes"] },
  "execution-quality": { title: "Qualité d’exécution et gestion des transactions", summary: "Deux traders partageant la même idée peuvent obtenir des résultats très différents. Ce cours mesure les raisons de cet écart.", modules: ["Déclencheurs d’entrée : ordre limite au niveau ou confirmation", "Exécutions partielles, entrées échelonnées et prix moyen", "Quand un stop suiveur aide et quand il réduit discrètement le résultat", "Alléger progressivement ou conserver la position jusqu’à un objectif unique", "Gérer une position ouverte lors d’une annonce à fort impact", "Mesurer votre glissement de prix selon les séances et les instruments", "Créer une grille d’évaluation de l’exécution après chaque transaction"] },
  "account-playbook": { title: "Plan de croissance du compte", summary: "Un plan étape par étape fondé sur les spécifications publiées de la société, et non sur des conseils génériques trouvés en ligne.", modules: ["Choisir un type de compte adapté au risque moyen par transaction", "Déterminer un premier dépôt que vous pouvez vous permettre de risquer", "Pourquoi un objectif de rendement mensuel est un minimum, jamais un quota", "Capitaliser ou retirer : quand choisir chaque option", "Les pratiques interdites et leurs raisons", "Réussir la vérification KYC dès la première demande : documents, noms et dates", "Ce qui change lorsque la taille du compte double", "Savoir quand réduire la taille ou arrêter de trader"] },
  "withdrawal-strategy": { title: "Stratégie de retrait et de capitalisation", summary: "Gérer un compte de trading comme une activité professionnelle : savoir quand retirer, capitaliser et développer le solde sans augmenter le risque par transaction.", modules: ["Comment la marge disponible limite les retraits possibles", "Retirer ou capitaliser, et le coût d’une mauvaise gestion des deux", "Se verser un revenu depuis un compte de trading", "Trader un compte plus important sans accroître le risque par transaction", "Gérer plusieurs comptes avec un seul profil vérifié", "Établir votre compte de résultat personnel annuel"] },
  "psychology-under-leverage": { title: "Psychologie et effet de levier", summary: "L’effet de levier modifie les comportements de façon mesurable, tout comme un solde suffisamment important. Ce cours identifie ces changements et les moyens d’y répondre.", modules: ["Comment l’effet de levier modifie le comportement face au risque dans les deux sens", "Engagements préalables qui résistent à une mauvaise matinée", "Tilt : quatre signes et l’intervention adaptée à chacun", "Risque lié à l’ennui lors d’une semaine calme et ses traces dans le journal", "Routines de performance inspirées des desks institutionnels", "Rédiger une règle que vous respecterez encore au sixième mois"] },
  "gold-and-metals": { title: "Or et métaux précieux", summary: "XAU/USD est l’instrument le plus négocié du desk et la cause la plus fréquente de drawdown inattendu. Découvrez son comportement.", modules: ["Facteurs qui influencent XAU/USD : taux réels, dollar et flux physiques", "Spécifications du contrat et valeur en dollars d’un point sur les métaux", "Régimes de volatilité de l’or et dimensionnement adapté", "Trader l’or lors des publications CPI et FOMC", "Sensibilité de l’argent à l’or et risques des entrées tardives", "Platine et palladium : carnets peu profonds et spreads larges", "Modèle de séance sur les métaux pendant le chevauchement Londres–New York"] },
  "indices-and-energy": { title: "Indices et énergie", summary: "Trois CFD sur indices américains aux comportements distincts, ainsi que les contrats sur le pétrole et le gaz naturel, qui sanctionnent vite les erreurs de dimensionnement.", modules: ["CFD sur indices au comptant, juste valeur et gap nocturne", "US30, NAS100 et SPX500 : trois instruments distincts", "Largeur du marché comme filtre de continuation", "WTI et Brent : ce que révèle leur écart de prix", "Lire la publication hebdomadaire des stocks de pétrole en direct", "Gaz naturel : saisonnalité et coût de détention", "Dimensionner le risque sur les indices et l’énergie dans la limite journalière de 5 %"] },
  "crypto-and-correlation": { title: "Cryptomonnaies et corrélations inter-actifs", summary: "Un marché ouvert 24 h/24 dans un cadre de risque 24 h/24 et 5 j/7, et l’effet d’une corrélation glissante avec les actions sur un portefeuille de positions ouvertes.", modules: ["Trader un marché 24 h/24 dans un cadre de risque 24 h/24 et 5 j/7", "Pourquoi le levier crypto est plafonné à 1:5 pour tous les niveaux", "Comportement du week-end et ouverture du lundi", "Corrélation glissante du Bitcoin avec le Nasdaq", "Dimensionner un instrument très volatil selon un risque fixe en dollars", "Conserver une exposition crypto lors du réajustement quotidien à 00:00 UTC"] },
};

const arCourses: Record<string, CourseText> = {
  "market-mechanics": { title: "آليات السوق وأنواع الأوامر", summary: "تعرّف إلى ماهية عقود الفروقات وكيفية تسعيرها، واختر الأمر الذي ينفّذ التعليمات التي تقصدها.", modules: ["كيفية تسعير عقد الفروقات وطبيعة تعرضك للسوق", "سعر العرض والطلب والسعر المتوسط والتكلفة الفعلية لعبور الفارق", "مقارنة أوامر السوق والأوامر المحددة وأوامر الإيقاف والإيقاف المحدد", "قراءة عمق السوق على cTrader", "الانزلاق السعري وأسباب اختلاف التنفيذ عن الرسم البياني", "أحجام العقود في الفوركس والمعادن والمؤشرات والعملات المشفرة", "الاحتفاظ بالصفقات لليلة وفهم التبييت اليومي", "إدخال أول أمر وتعديله عبر Web Terminal"] },
  "pips-lots-leverage": { title: "حساب النقاط واللوت والرافعة المالية", summary: "الحسابات التي يجريها المتداول الجاد قبل فتح الصفقة، مع تطبيقها على مواصفات العقود الفعلية.", modules: ["النقاط والبوينتات وحركات الأسعار: مقدار الحركة وقيمتها", "اللوت القياسي والميني والميكرو عمليًا", "قيمة النقطة في الأزواج المسعّرة بالدولار والأزواج المتقاطعة", "التعرض الاسمي مقابل الهامش المطلوب فعليًا", "ما الذي تغيّره رافعة 1:100 وما الذي لا تغيّره", "مستوى الهامش ونداء الهامش وحد الإغلاق الإجباري", "عشرة أمثلة عملية لتحديد حجم الصفقات عبر أربع فئات من الأصول"] },
  "session-structure": { title: "جلسات التداول والسيولة وساعات السوق", summary: "لا تبقى السيولة ثابتة. ترسم هذه الدورة يوم التداول وفق UTC وتربط اختيار الأداة بالساعات الأكثر نشاطًا.", modules: ["ساعات سيدني وطوكيو ولندن ونيويورك وفق UTC", "لماذا يوفر تداخل لندن ونيويورك أعمق دفتر أوامر", "سلوك الفارق عند افتتاح الجلسة الآسيوية وعند التبييت اليومي", "مواءمة اختيار الأداة مع تقلبات الجلسة", "تقويم العطلات والجلسات القصيرة ومخاطر ضعف السيولة", "إعداد خطة جلسة قابلة للتكرار كل أسبوع"] },
  "risk-first-sizing": { title: "تحديد حجم الصفقة انطلاقًا من المخاطر", summary: "حدّد الخسارة التي تقبلها، ثم دع مسافة وقف الخسارة تحدد حجم الصفقة. إنها عادة أساسية للاستمرار في التداول.", modules: ["المخاطرة بنسبة ثابتة وقدرتها على تجاوز سلاسل الخسائر", "تحويل مسافة وقف الخسارة إلى حجم لوت في ثلاث خطوات", "تحديد حجم عقود فروقات الذهب والنفط والمؤشرات من دون حاسبة نقاط", "جدول التعافي من التراجع ولماذا تتطلب خسارة 30% ربحًا قدره 42.9%", "الارتباط: متى تكون ثلاث صفقات في حقيقتها فكرة واحدة", "خفض حجم الصفقة قبل إعلان مؤثر وإعادته بعده", "إنشاء ورقة موجزة لتحديد حجم الصفقة قبل التداول", "مراجعة الشهر الماضي لاكتشاف الانحراف في أحجام الصفقات"] },
  "expectancy-and-review": { title: "القيمة المتوقعة وسجل التداول والمراجعة", summary: "ميّز بين شهر خاسر واستراتيجية فقدت ميزتها باستخدام سجل صفقاتك بدلًا من الانطباعات.", modules: ["معدل الربح ومضاعف R ولماذا تتفوق القيمة المتوقعة على الدقة", "سجل يوثّق القرار لا النتيجة وحدها", "تصنيف الإعدادات لاستبعاد ما يسبب الخسائر", "إجراء محاكاة مونت كارلو على صفقاتك", "التمييز بين التذبذب المعتاد وفقدان الاستراتيجية لميزتها", "المراجعة الشهرية التي يجريها فريق التداول لمحفظته"] },
  "structure-and-levels": { title: "بنية السوق واختيار المستويات", summary: "ارسم المستويات بإتقان ولا تواصل تحريكها. اتبع منهجًا متكررًا لاختيار الأسعار القليلة المهمة.", modules: ["بنية القمم والقيعان المتأرجحة وحالات فشلها", "تحديد المستويات مرة واحدة وتجنب تغييرها خلال الجلسة", "مناطق العرض والطلب مقارنة بخطوط الأسعار المفردة", "التوافق بين الأطر الزمنية دون إفراط في التحليل", "الحجم وحجم التداول بالنقرات: ما تعرضه MetaTrader فعليًا", "تحديد وقف الخسارة وفق ATR بدلًا من الأرقام المستديرة", "تكوين الاختراق الكاذب وكيفية التداول عكسه بأمان", "روتين تحديد مستويات ما قبل السوق خلال عشرين دقيقة"] },
  "execution-quality": { title: "جودة التنفيذ وإدارة الصفقات", summary: "قد يحقق متداولان يحملان الفكرة نفسها نتائج مختلفة جدًا. تشرح هذه الدورة الفارق وتقيسه بدلًا من افتراضه.", modules: ["محفزات الدخول: أمر محدد عند المستوى أو انتظار التأكيد", "التنفيذ الجزئي والدخول المتدرج ومتوسط السعر", "متى يفيد وقف الخسارة المتحرك ومتى يقلل أرباحك تدريجيًا", "تقليص الصفقة تدريجيًا أو الاحتفاظ بها لهدف واحد", "إدارة صفقة مفتوحة أثناء صدور خبر بالغ التأثير", "قياس انزلاقك السعري حسب الجلسة والأداة", "إعداد بطاقة تقييم للتنفيذ بعد الصفقة"] },
  "account-playbook": { title: "خطة تنمية الحساب", summary: "خطة مرحلية لتنمية حساب التداول وفق المواصفات المنشورة للشركة، بدلًا من النصائح العامة على الإنترنت.", modules: ["اختيار نوع حساب يناسب متوسط المخاطرة لكل صفقة", "تحديد إيداع أول يمكنك تحمل مخاطرته", "لماذا يمثل هدف العائد الشهري حدًا أدنى لا حصة إلزامية", "متى تختار إعادة استثمار الأرباح ومتى تسحبها", "الممارسات المحظورة والأسباب وراءها", "اجتياز التحقق من الهوية KYC من المرة الأولى: المستندات والأسماء والتواريخ", "ما الذي يتغير عندما يتضاعف حجم الحساب", "معرفة متى تخفض الحجم ومتى تتوقف عن التداول"] },
  "withdrawal-strategy": { title: "استراتيجية السحب وإعادة استثمار الأرباح", summary: "تعامل مع حساب التداول كنشاط تجاري: اعرف متى تسحب ومتى تعيد استثمار الأرباح وكيف تنمّي الرصيد دون زيادة المخاطرة لكل صفقة.", modules: ["كيف يحد الهامش الحر مما يمكنك سحبه فعليًا", "السحب أو إعادة الاستثمار وتكلفة سوء إدارة الخيارين", "تخصيص دخل لنفسك من حساب التداول", "تداول حساب أكبر من دون زيادة المخاطرة لكل صفقة", "إدارة عدة حسابات عبر ملف موحّد تم التحقق منه", "إعداد بيان أرباح وخسائر شخصي للسنة"] },
  "psychology-under-leverage": { title: "سيكولوجية التداول مع الرافعة المالية", summary: "تغيّر الرافعة السلوك بطرق قابلة للقياس، وكذلك يفعل الرصيد الكبير. تحدد الدورة هذه التغييرات وتقدم وسيلة للتعامل مع كل منها.", modules: ["كيف تغيّر الرافعة السلوك تجاه المخاطر في الاتجاهين", "التزامات مسبقة تصمد أمام صباح سيئ", "التداول بدافع الانفعال: أربع علامات والتدخل المناسب لكل منها", "مخاطر الملل خلال أسبوع هادئ وكيف تظهر في سجل التداول", "روتين الأداء المستمد من فرق التداول المؤسسية", "كتابة قاعدة ستواصل الالتزام بها بعد ستة أشهر"] },
  "gold-and-metals": { title: "الذهب ومجموعة المعادن الثمينة", summary: "يُعد XAU/USD أكثر الأدوات تداولًا لدى الفريق وأكثر أسباب التراجع المفاجئ شيوعًا. تعرّف إلى سلوكه.", modules: ["محركات XAU/USD: العوائد الحقيقية والدولار والتدفقات المادية", "مواصفات العقد وقيمة النقطة بالدولار للمعادن", "أنظمة تقلب الذهب وكيفية تحديد الحجم لكل منها", "تداول الذهب أثناء صدور بيانات CPI وقرارات FOMC", "حساسية الفضة لتحركات الذهب ومخاطر الدخول المتأخر", "البلاتين والبلاديوم: دفاتر أوامر محدودة وفوارق واسعة", "نموذج جلسة للمعادن خلال تداخل لندن ونيويورك"] },
  "indices-and-energy": { title: "المؤشرات والطاقة", summary: "ثلاثة عقود فروقات على مؤشرات أمريكية مختلفة، إلى جانب عقود النفط والغاز الطبيعي التي تكشف أخطاء تحديد حجم الصفقة بسرعة.", modules: ["عقود فروقات المؤشرات النقدية والقيمة العادلة والفجوة الليلية", "US30 وNAS100 وSPX500: ثلاث أدوات مختلفة", "اتساع السوق كمرشح لاستمرار الحركة", "النفط WTI مقابل Brent وما يكشفه الفارق بينهما", "قراءة تقرير مخزونات النفط الأسبوعي عند صدوره", "الغاز الطبيعي: الموسمية وتكلفة الاحتفاظ بالصفقة", "مواءمة مخاطر المؤشرات والطاقة مع الحد اليومي البالغ 5%"] },
  "crypto-and-correlation": { title: "العملات المشفرة والارتباط بين فئات الأصول", summary: "سوق يعمل على مدار الساعة ضمن إطار مخاطر يمتد خمسة أيام أسبوعيًا، وتأثير الارتباط المتحرك بالأسهم على محفظة الصفقات المفتوحة.", modules: ["تداول سوق يعمل 24/7 ضمن إطار مخاطر 24/5", "لماذا تُحدد الرافعة على العملات المشفرة بحد أقصى 1:5 في جميع الباقات", "سلوك السوق في عطلة نهاية الأسبوع وافتتاح يوم الاثنين", "الارتباط المتحرك بين Bitcoin ومؤشر Nasdaq", "تحديد حجم أداة شديدة التقلب وفق مخاطرة ثابتة بالدولار", "الاحتفاظ بتعرض للعملات المشفرة خلال إعادة الضبط اليومية عند 00:00 UTC"] },
};

const frPath: PathText[] = [
  { title: "Maîtriser les calculs", why: "Presque tous les comptes clôturés pour dépassement que nous examinons comportent au moins une position dimensionnée au ressenti. Les calculs doivent devenir automatiques avant tout le reste.", outcome: "Vous pouvez énoncer votre exposition, la valeur de votre pip et votre perte maximale avant de cliquer sur Acheter." },
  { title: "Construire le cadre de risque", why: "Le règlement est une contrainte à intégrer dès la conception, pas une surprise. Les traders qui fixent une limite journalière personnelle inférieure au plafond la dépassent rarement.", outcome: "Un budget de risque écrit qui vous maintient sous les drawdowns de 5 % par jour et de 10 % au total, même lors de votre pire journée." },
  { title: "Affiner l’entrée", why: "La technique arrive volontairement en troisième position. Une entrée précise dans un cadre de risque défaillant ne fait que perdre de l’argent avec plus de précision.", outcome: "Une routine préouverture reproductible et un relevé mesurable de la qualité d’exécution de votre plan." },
  { title: "Apprendre à analyser", why: "Impossible d’améliorer un processus qui n’est pas mesuré, ni de défendre une stratégie sans données chiffrées.", outcome: "Assez d’éléments pour distinguer un drawdown dû à la variance d’un avantage qui ne fonctionne plus." },
  { title: "Faire croître le compte", why: "Un compte réel est différent d’un compte démo. Étudiez le rythme et les pratiques interdites avant votre première transaction, pas après une mauvaise semaine.", outcome: "Un plan de croissance, une liste de contrôle KYC et une compréhension honnête de l’effet du levier sur votre comportement." },
  { title: "Se spécialiser et passer à l’échelle", why: "Une fois les bases, le risque et l’exécution maîtrisés, spécialisez-vous sur les actifs et les décisions de portefeuille qui correspondent à votre méthode.", outcome: "Une approche cohérente pour retirer, diversifier les actifs et gérer les corrélations à mesure que le compte grandit." },
];

const arPath: PathText[] = [
  { title: "إتقان الحسابات", why: "تتضمن معظم الحسابات التي نراجعها بعد تجاوز الحدود صفقة واحدة على الأقل حُدد حجمها بالتخمين. يجب أن تصبح الحسابات تلقائية قبل تعلم أي شيء آخر.", outcome: "تستطيع تحديد تعرضك وقيمة النقطة وأسوأ خسارة محتملة قبل الضغط على الشراء." },
  { title: "بناء إطار لإدارة المخاطر", why: "القواعد إطار ينبغي تصميم خطتك وفقه، لا مفاجأة تكتشفها لاحقًا. ونادرًا ما يتجاوز المتداولون الذين يضعون حدًا يوميًا شخصيًا أدنى من الحد الرسمي ذلك الحد.", outcome: "ميزانية مخاطر مكتوبة تُبقيك ضمن تراجع يومي قدره 5% وإجمالي قدره 10% حتى في أسوأ أيامك." },
  { title: "تحسين نقطة الدخول", why: "يأتي الجانب الفني ثالثًا عن قصد. فالدخول الدقيق ضمن إطار مخاطر غير سليم لا يفعل سوى خسارة المال بدقة أكبر.", outcome: "روتين متكرر لما قبل افتتاح السوق وسجل قابل للقياس لمدى جودة تنفيذ خطتك." },
  { title: "تعلّم المراجعة", why: "لا يمكنك تحسين عملية لا تقيسها، ولا مواصلة استراتيجية لا تستطيع دعمها بالأرقام.", outcome: "أدلة كافية للتمييز بين تراجع ناتج عن التذبذب المعتاد واستراتيجية فقدت ميزتها." },
  { title: "تنمية الحساب", why: "يختلف الحساب الحقيقي عن الحساب التجريبي. ادرس وتيرة التداول والممارسات المحظورة قبل أول صفقة، لا بعد أسبوع سيئ.", outcome: "خطة للنمو وقائمة تحقق KYC وفهم واقعي لتأثير الرافعة على سلوكك." },
  { title: "التخصص والتوسع", why: "بعد إتقان الأساسيات والمخاطر والتنفيذ، تخصص في الأصول وقرارات المحفظة التي تلائم منهجك.", outcome: "منهج متسق للسحب وتنويع الأصول وإدارة الارتباطات مع نمو الحساب." },
];

const frGlossary: Record<string, string> = {
  "Allocation cap": "Le capital total maximal que vous pouvez détenir simultanément sur vos comptes, fixé à 400 000 $ d’allocation initiale cumulée. Seules les étapes de progression accordées par le desk du risque permettent de dépasser ce plafond.",
  AML: "Lutte contre le blanchiment de capitaux : contrôles visant à empêcher l’utilisation des moyens de retrait pour transférer des fonds d’origine criminelle. Ils comprennent la vérification d’identité, le filtrage des sanctions et, si nécessaire, les questions sur l’origine des fonds.",
  Ask: "Prix auquel un instrument peut être acheté à l’instant. Il est supérieur au bid ; l’écart entre les deux correspond au spread payé pour ouvrir une position acheteuse.",
  ATR: "Average True Range, indicateur de l’amplitude habituelle d’un instrument sur une période donnée. Un stop calculé comme multiple de l’ATR s’adapte à la volatilité actuelle plutôt qu’à un niveau rond du graphique.",
  Balance: "Montant du compte hors positions ouvertes. Le solde change à la clôture d’une transaction ou au règlement d’un dépôt ou d’un retrait, tandis que l’equity évolue avec les positions ouvertes.",
  Bid: "Prix auquel un instrument peut être vendu à l’instant. Les graphiques des plateformes cotées sont établis à partir du bid ; une position acheteuse semble donc s’ouvrir légèrement sous la bougie sélectionnée.",
  Breach: "Dépassement d’une limite ferme de risque, le plus souvent le drawdown quotidien maximal de 5 % ou le drawdown total maximal de 10 %. La détection est effectuée côté serveur et entraîne la clôture du compte au moment du dépassement.",
  Chargeback: "Annulation d’un paiement demandée auprès de l’émetteur de votre carte plutôt qu’auprès de Connect Funded. Elle entraîne le gel des comptes associés pendant l’enquête ; une demande de retrait auprès du support est plus rapide.",
  "Contract size": "Quantité de sous-jacent représentée par un lot. Un lot Forex standard représente 100 000 unités de la devise de base ; un lot d’or représente 100 onces troy. Cette taille convertit un mouvement de prix en gain ou perte.",
  "Copy trading": "Reproduction d’ordres d’un compte à l’autre. La copie entre vos propres comptes est autorisée si l’exposition cumulée reste dans les limites de marge. Copier un signal tiers reste à vos risques.",
  Correlation: "Degré de mouvement commun entre deux instruments. Des positions acheteuses sur EUR/USD, GBP/USD et AUD/USD constituent presque une seule position vendeuse sur le dollar et doivent être budgétées comme une seule idée.",
  "Depth of market": "Affichage des ordres d’achat et de vente en attente à chaque niveau de prix, aussi appelé Level II. cTrader l’affiche nativement : il indique où se trouve la taille disponible, et non les prix déjà atteints.",
  Equity: "Solde du compte augmenté du gain ou de la perte flottante de toutes les positions ouvertes. C’est la valeur utilisée pour le contrôle de marge ; une perte latente peut donc déclencher un appel de marge avant la clôture.",
  Expectancy: "Résultat moyen d’une transaction dans votre système, exprimé en R. Un taux de réussite de 40 %, des gains de 3R et des pertes de 1R donnent une espérance de +0,6R.",
  "Expert advisor": "Stratégie automatisée exécutée dans MetaTrader et écrite en MQL5. Les expert advisors, indicateurs personnalisés et exécutions algorithmiques sont autorisés s’ils négocient le marché et non le flux de cotation.",
  "Free margin": "Equity moins la marge immobilisée pour les positions ouvertes. Cette valeur détermine la capacité à ouvrir de nouvelles positions et le montant retirable à l’instant.",
  Gap: "Saut de prix entre la clôture d’une séance et l’ouverture de la suivante, sans prix négociable intermédiaire. Un stop ne protège pas pendant un gap ; l’exposition du week-end doit donc être dimensionnée plus prudemment.",
  Hedging: "Détention de positions opposées sur le même instrument ou sur des instruments étroitement liés. La couverture au sein d’un compte est autorisée ; répartir la même exposition entre des comptes ou des traders est interdit.",
  KYC: "Know Your Customer : vérification d’identité effectuée avant le premier retrait. Elle exige une pièce d’identité officielle avec photo et un justificatif de domicile de moins de trois mois, téléversés dans l’espace client.",
  "Latency arbitrage": "Exploitation du délai entre l’affichage d’un prix sur une place plus rapide et son apparition dans notre flux. Cette pratique cible le mécanisme de cotation plutôt que le marché et est interdite.",
  Leverage: "Rapport entre l’exposition notionnelle et la marge utilisée. Le levier proposé peut atteindre 1:100 sur le Forex, 1:50 sur les métaux et indices, 1:200 sur l’énergie, 1:100 sur les CFD actions et 1:5 sur les cryptomonnaies. Il modifie la marge, jamais le risque.",
  "Limit order": "Instruction de négocier à un prix déterminé ou meilleur. L’exécution ne sera pas moins favorable que le prix indiqué, mais l’ordre peut ne jamais être exécuté si le marché traverse le niveau sans liquidité disponible.",
  Liquidity: "Quantité pouvant être négociée sans déplacer le prix. Une forte liquidité s’accompagne de spreads serrés et d’exécutions prévisibles ; une faible liquidité favorise le slippage, l’élargissement des spreads et les fausses cassures.",
  Lot: "Unité standard de taille de transaction. Un lot Forex standard vaut 100 000 unités de devise de base ; un mini-lot vaut 0,1 lot et un micro-lot 0,01. Chaque instrument conserve sa propre taille de contrat.",
  Margin: "Part de l’equity immobilisée pour soutenir une position ouverte, calculée à partir de l’exposition notionnelle et du levier. La marge est une exigence de garantie, pas un coût, et elle est libérée à la clôture.",
  "Margin call": "État d’alerte atteint lorsque l’equity tombe à 100 % de la marge utilisée. Il faut alors ajouter des fonds ou réduire l’exposition ; les positions sont clôturées lorsque la limite de perte de 5 % est atteinte.",
  "Market order": "Instruction d’exécuter immédiatement au meilleur prix disponible. Elle garantit l’exécution, pas le prix ; en période de forte activité, l’écart entre le cours affiché et le cours obtenu apparaît comme du slippage.",
  Mid: "Cours médian entre le bid et l’ask. Les analyses et la plupart des graphiques publiés l’utilisent pour neutraliser le spread ; un backtest fondé sur le cours médian peut donc surestimer le résultat réel.",
  "Minimum trading days": "Quatre jours distincts pendant lesquels au moins une position doit être ouverte avant de terminer une phase. C’est un minimum, pas un objectif : aucune échéance calendaire ne justifie de forcer une transaction.",
  "Notional exposure": "Valeur totale de marché contrôlée par une position : nombre de lots multiplié par la taille du contrat puis par le prix. Deux lots EUR/USD à 1,0850 représentent 217 000 $ d’exposition notionnelle, quelle que soit la marge utilisée.",
  "Negative balance protection": "Engagement garantissant qu’un compte de détail ne passe pas sous zéro. Si un gap rend le solde négatif avant la clôture des positions, il est ramené à zéro aux frais de la société.",
  Pip: "Plus petite variation conventionnelle cotée d’une paire de devises : 0,0001 pour la plupart des paires majeures et 0,01 pour les paires en yen. Sur un lot standard d’une paire cotée en USD, un pip vaut 10 $.",
  Point: "Plus petite variation cotable par la plateforme, un rang décimal plus fine qu’un pip sur un flux à cinq décimales. Dix points font un pip sur EUR/USD. Les indices et métaux sont généralement cotés en points.",
  "Margin level": "Equity divisée par la marge utilisée, exprimée en pourcentage. Cette valeur indique la proximité d’un appel de marge ; le stop-out du compte intervient à sa limite de perte de 5 %.",
  "Proof of address": "Facture de service, relevé bancaire ou courrier officiel daté de moins de trois mois et indiquant votre nom et adresse résidentielle. Ce document complète la pièce d’identité exigée pour le KYC.",
  "R-multiple": "Résultat d’une transaction exprimé en unités du risque engagé. Risquer 500 $ pour gagner 1 500 $ correspond à +3R. Cette mesure permet de comparer les résultats entre tailles de compte et étapes de progression.",
  Rollover: "Moment quotidien où les positions ouvertes passent à la date de valeur suivante. Il intervient à 21:00 UTC sur la plupart des instruments et peut s’accompagner de spreads larges ; Connect Funded ne facture pas de swap.",
  "Sanctions screening": "Vérification du demandeur et de ses moyens de paiement par rapport aux listes de sanctions internationales et de personnes politiquement exposées. Une correspondance bloque le financement jusqu’à résolution.",
  "Session overlap": "Période où deux grands centres financiers sont actifs simultanément. Le chevauchement Londres–New York, approximativement de 12:00 à 16:00 UTC, offre généralement la plus grande profondeur et les spreads les plus serrés sur le Forex, les métaux et les indices américains.",
  Slippage: "Écart entre le prix attendu et le prix d’exécution. C’est une conséquence normale d’un ordre au marché dans un marché mobile ; il est utile de le mesurer par instrument et par séance.",
  "Source of funds": "Justificatifs établissant l’origine des fonds déposés. Ils ne sont demandés que si un schéma de dépôts ou une alerte de sanctions le nécessite et sont conservés selon les délais de la politique AML.",
  Spread: "Écart entre bid et ask, et coût immédiat d’ouverture d’une position. Les spreads EUR/USD sont annoncés à partir de 0,0 pip ; ils s’élargissent au rollover, lors des annonces importantes et pendant les séances peu liquides.",
  "Stop order": "Instruction qui devient un ordre au marché dès que le prix déclencheur est atteint. Elle garantit une action, pas un prix ; lors d’un gap, un stop protecteur peut être exécuté bien au-delà du niveau fixé.",
  "Stop-out": "Clôture automatique des positions lorsque le compte atteint sa limite de perte de 5 %. Surveillez le risque disponible et réduisez l’exposition avant ce seuil.",
  Swap: "Ajustement de financement que certains courtiers appliquent aux positions conservées la nuit. Connect Funded ne facture pas de swap sur ses comptes.",
  Tick: "Une mise à jour du flux de prix. Le volume en ticks compte les mises à jour et non les contrats ; l’histogramme MetaTrader indique donc l’activité du flux, pas le volume réellement négocié.",
  "Tick scalping": "Ouverture répétée de positions de quelques ticks en profitant de cotations momentanément obsolètes. Comme l’arbitrage de latence, cette pratique cible le flux plutôt que le marché et est interdite.",
  "Trailing stop": "Stop qui suit le prix à distance fixe lorsque la position évolue favorablement. Il protège une partie du mouvement, mais peut réduire de nombreuses positions gagnantes ; il convient davantage aux tendances qu’aux retours à la moyenne.",
  Volatility: "Ampleur habituelle des mouvements de prix sur une période. Elle doit guider la taille de position : un lot fixe représente des risques très différents lors d’une séance calme ou agitée.",
};

const arGlossary: Record<string, string> = {
  "Allocation cap": "الحد الأقصى لرأس مال الشركة الذي يمكنك الاحتفاظ به عبر جميع حساباتك في الوقت نفسه، ويبلغ 400,000 دولار من إجمالي التخصيص الابتدائي. لا يمكن تجاوزه إلا عبر مراحل التوسع التي يمنحها فريق المخاطر لكل حساب.",
  AML: "مكافحة غسل الأموال: ضوابط تمنع استخدام وسائل السحب لنقل عائدات الجرائم. وتشمل عمليًا التحقق من الهوية قبل التمويل، وفحص العقوبات على الحسابات، والاستفسار عن مصدر الأموال عند الحاجة.",
  Ask: "السعر الذي يمكنك شراء الأداة به الآن. يكون أعلى من سعر العرض، والفرق بينهما هو الفارق الذي تدفعه لفتح صفقة شراء.",
  ATR: "متوسط المدى الحقيقي، وهو مقياس لمقدار تحرك الأداة عادة خلال فترة محددة. يساعد تحديد وقف الخسارة كمضاعف لـ ATR على مواءمة المخاطر مع التقلب الحالي بدلًا من رقم دائري على الرسم.",
  Balance: "رصيد الحساب النقدي باستثناء الصفقات المفتوحة. يتغير عند إغلاق صفقة أو تسوية إيداع أو سحب، بينما تتغير حقوق الملكية مع الصفقات المفتوحة.",
  Bid: "السعر الذي يمكنك بيع الأداة به الآن. تعرض المنصات الرسوم عادةً استنادًا إلى سعر العرض، لذلك قد تبدو صفقة الشراء وكأنها افتُتحت أسفل الشمعة التي نقرت عليها قليلًا.",
  Breach: "مخالفة حد صارم للمخاطر، وغالبًا ما تكون تجاوز التراجع اليومي الأقصى 5% أو التراجع الإجمالي الأقصى 10%. يُكتشف التجاوز على الخادم ويُغلق الحساب عند وقوعه.",
  Chargeback: "عكس عملية دفع يطلبه العميل من جهة إصدار البطاقة بدلًا من طلبه منا. يؤدي ذلك إلى تجميد الحسابات المرتبطة ريثما يجري التحقيق؛ وعادةً يكون طلب السحب عبر الدعم أسرع.",
  "Contract size": "كمية الأصل الأساسي التي يمثلها اللوت الواحد. يمثل اللوت القياسي في الفوركس 100,000 وحدة من العملة الأساسية، ويمثل لوت الذهب 100 أونصة تروي. يحول حجم العقد تغير السعر إلى ربح أو خسارة.",
  "Copy trading": "نسخ الأوامر من حساب إلى آخر. يُسمح بالنسخ بين حساباتك ما دام التعرض الإجمالي ضمن حدود الهامش. أما نسخ إشارات جهة خارجية فيبقى على مسؤوليتك.",
  Correlation: "درجة تحرك أداتين في الاتجاه نفسه. إن فتح صفقات شراء على EUR/USD وGBP/USD وAUD/USD يشبه إلى حد كبير صفقة بيع واحدة على الدولار، لذا ينبغي احتساب مخاطرها كفكرة واحدة.",
  "Depth of market": "عرض لأوامر الشراء والبيع المعلقة عند مستويات الأسعار المختلفة، ويُعرف أيضًا باسم Level II. تعرضه cTrader مباشرةً، وهو يوضح أماكن الأوامر المنتظرة لا الأسعار التي تحققت بالفعل.",
  Equity: "رصيد الحساب مضافًا إليه الربح أو الخسارة العائمة لجميع الصفقات المفتوحة. يُستخدم هذا الرقم في فحص الهامش، لذلك قد تؤدي خسارة غير محققة إلى نداء هامش قبل إغلاق الصفقة.",
  Expectancy: "متوسط نتيجة الصفقة في نظامك، ويُعبّر عنها بوحدات R. فمعدل ربح 40% مع أرباح 3R وخسائر 1R ينتج قيمة متوقعة قدرها +0.6R.",
  "Expert advisor": "استراتيجية آلية تعمل داخل MetaTrader ومكتوبة بلغة MQL5. يُسمح بالمستشارين الخبراء والمؤشرات المخصصة والتنفيذ الخوارزمي إذا كانت تتداول السوق لا تدفق الأسعار.",
  "Free margin": "حقوق الملكية مطروحًا منها الهامش المحجوز للصفقات المفتوحة. يحدد هذا الرقم مقدار ما يمكنك فتحه من صفقات إضافية وما يمكنك سحبه الآن.",
  Gap: "قفزة سعرية بين إغلاق جلسة وافتتاح التالية من دون سعر قابل للتداول بينهما. لا يحمي وقف الخسارة خلال الفجوة، لذلك يجب تحديد تعرض عطلة نهاية الأسبوع بحذر أكبر.",
  Hedging: "الاحتفاظ بصفقات متعاكسة على الأداة نفسها أو أدوات مترابطة. يُسمح بالتحوط داخل الحساب الواحد؛ أما توزيع التعرض نفسه بين حسابين أو متداولين فهو ممارسة محظورة.",
  KYC: "اعرف عميلك: إجراء التحقق من الهوية قبل صرف أول عملية سحب. يتطلب وثيقة هوية حكومية تحمل صورة وإثبات عنوان لا يتجاوز تاريخه ثلاثة أشهر، ويُرفعان عبر بوابة العميل.",
  "Latency arbitrage": "استغلال التأخير بين ظهور السعر في منصة أسرع وظهوره في تدفق الأسعار لدينا. تستهدف هذه الممارسة آلية التسعير بدلًا من السوق، وهي محظورة.",
  Leverage: "النسبة بين قيمة التعرض الاسمية والهامش الذي يستهلكه. يصل الحد إلى 1:100 للفوركس، و1:50 للمعادن والمؤشرات، و1:200 للطاقة، و1:100 لعقود الأسهم مقابل الفروقات، و1:5 للعملات المشفرة. تغيّر الرافعة الهامش ولا تغيّر المخاطر.",
  "Limit order": "تعليمات للتداول بسعر محدد أو أفضل. لن يُنفذ الأمر بسعر أسوأ من المحدد، لكن قد لا يُنفذ إذا تجاوز السوق المستوى من دون توفر حجم كافٍ.",
  Liquidity: "حجم التداول الممكن دون التأثير في السعر. تعني السيولة العميقة فروقًا ضيقة وتنفيذًا أكثر قابلية للتوقع؛ أما ضعفها فيزيد الانزلاق واتساع الفارق والاختراقات الكاذبة.",
  Lot: "وحدة قياسية لحجم الصفقة. يعادل اللوت القياسي 100,000 وحدة من العملة الأساسية في الفوركس، والميني 0.1 لوت، والميكرو 0.01. ولكل أداة حجم عقد خاص بها.",
  Margin: "جزء من حقوق الملكية يُحجز لدعم الصفقة المفتوحة، ويُحدد وفق التعرض الاسمي والرافعة. الهامش ضمان مطلوب وليس تكلفة، ويُحرر عند إغلاق الصفقة.",
  "Margin call": "حالة تحذير تبدأ عندما تنخفض حقوق الملكية إلى 100% من الهامش المستخدم. عندها يلزم إضافة أموال أو خفض التعرض؛ وتُغلق الصفقات عند بلوغ حد الخسارة البالغ 5%.",
  "Market order": "تعليمات للتداول فورًا بأفضل سعر متاح. تضمن تنفيذ الأمر لا السعر؛ وفي ظروف السوق السريعة يظهر الفرق بين السعر المعروض والتنفيذ على هيئة انزلاق سعري.",
  Mid: "السعر المتوسط بين العرض والطلب. تستخدمه التحليلات ومعظم الرسوم المنشورة لإزالة أثر الفارق، ولذلك قد تبالغ نتائج الاختبار التاريخي المبني عليه في تقدير النتيجة الفعلية.",
  "Minimum trading days": "أربعة أيام منفصلة يجب فتح صفقة واحدة على الأقل في كل منها قبل إكمال المرحلة. هذا حد أدنى لا هدف، ولا يوجد موعد نهائي يبرر فرض صفقة لاستيفائه.",
  "Notional exposure": "القيمة السوقية الكاملة التي تتحكم بها الصفقة: عدد اللوتات مضروبًا في حجم العقد ثم السعر. يمثل لوتان من EUR/USD بسعر 1.0850 تعرضًا اسميًا قدره 217,000 دولار بصرف النظر عن الهامش.",
  "Negative balance protection": "التزام بألا ينخفض حساب العميل دون الصفر. إذا أدت فجوة سعرية إلى رصيد سلبي قبل إغلاق الصفقات، يُعاد الرصيد إلى الصفر على نفقتنا.",
  Pip: "أصغر تغير تقليدي في تسعير زوج عملات: 0.0001 لمعظم الأزواج الرئيسية و0.01 لأزواج الين. تبلغ قيمة النقطة 10 دولارات في اللوت القياسي لزوج مسعّر بالدولار.",
  Point: "أصغر تغير تعرضه المنصة، وهو منزلة عشرية أدق من النقطة على تدفق من خمس خانات. تساوي عشرة بوينتات نقطة واحدة في EUR/USD. وتُقاس المؤشرات والمعادن عادةً بالبوينت.",
  "Margin level": "حقوق الملكية مقسومة على الهامش المستخدم، معبّرًا عنها بنسبة مئوية. يوضح مدى قرب الحساب من نداء الهامش، ويُفعّل الإغلاق الإجباري عند حد الخسارة 5%.",
  "Proof of address": "فاتورة خدمات أو كشف حساب بنكي أو خطاب حكومي صادر خلال الأشهر الثلاثة الماضية ويظهر الاسم وعنوان السكن. وهو أحد مستندَي KYC المطلوبين إلى جانب وثيقة الهوية المصورة.",
  "R-multiple": "نتيجة الصفقة معبّرًا عنها بوحدات المخاطرة. المخاطرة بـ500 دولار لتحقيق 1,500 دولار تعادل +3R. تتيح هذه الطريقة مقارنة النتائج بين أحجام الحسابات ومراحل التوسع.",
  Rollover: "الوقت اليومي الذي تُرحّل فيه الصفقات المفتوحة إلى تاريخ القيمة التالي. يحدث عند 21:00 UTC لمعظم الأدوات وقد تتسع الفروق فيه؛ ولا تفرض Connect Funded رسوم تبييت.",
  "Sanctions screening": "فحص المتقدم ووسائل الدفع مقابل قوائم العقوبات الدولية وقوائم الأشخاص المعرضين سياسيًا. يجري عند التسجيل ودوريًا؛ وتمنع المطابقة الإيجابية التمويل إلى حين حلها.",
  "Session overlap": "الفترة التي تعمل فيها منطقتان ماليتان رئيسيتان في الوقت نفسه. يوفر تداخل لندن ونيويورك، تقريبًا من 12:00 إلى 16:00 UTC، أعمق دفتر أوامر وأضيق الفروق يوميًا في الفوركس والمعادن والمؤشرات الأمريكية.",
  Slippage: "الفرق بين السعر المتوقع وسعر التنفيذ. وهو نتيجة طبيعية للتداول بأمر سوق في سوق متحرك؛ ومن المفيد قياسه لكل أداة وجلسة بدل اعتباره ضوضاء.",
  "Source of funds": "مستندات تثبت مصدر الأموال المودعة. لا تُطلب إلا عندما يستدعي نمط الإيداع أو تنبيه العقوبات ذلك، وتُحفظ وفق مدد الاحتفاظ المحددة في سياسة AML.",
  Spread: "الفارق بين سعري العرض والطلب والتكلفة المباشرة لفتح الصفقة. تبدأ الفروق المعلنة على EUR/USD من 0.0 نقطة، وتتسع عند التبييت والأخبار المؤثرة وضعف السيولة.",
  "Stop order": "تعليمات تتحول إلى أمر سوق عند وصول السعر إلى مستوى التفعيل. تضمن تنفيذ الإجراء لا سعره؛ وقد يُنفذ وقف الحماية بسعر أسوأ بكثير عند حدوث فجوة.",
  "Stop-out": "إغلاق تلقائي للصفقات عندما يبلغ الحساب حد الخسارة البالغ 5%. راقب المخاطر المتاحة وخفّض التعرض قبل بلوغ هذا الحد.",
  Swap: "تعديل تمويلي يفرضه بعض الوسطاء على الصفقات المحتفظ بها لليلة. لا تفرض Connect Funded رسوم تبييت على حساباتها.",
  Tick: "تحديث واحد لتدفق الأسعار. يحصي حجم التداول بالنقرات التحديثات لا العقود، لذلك يقيس مخطط الحجم في MetaTrader نشاط التدفق لا حجم التداول الفعلي.",
  "Tick scalping": "فتح صفقات متكررة لا تتجاوز بضع نقرات للاستفادة من أسعار قديمة مؤقتًا. مثل المراجحة على زمن التأخير، تستهدف هذه الممارسة تدفق الأسعار لا السوق وهي محظورة.",
  "Trailing stop": "وقف خسارة يتبع السعر بمسافة ثابتة عندما تتحرك الصفقة لصالحك. يحافظ على جزء من المكاسب، لكنه قد يحول صفقات رابحة كثيرة إلى أرباح صغيرة؛ ويناسب الاتجاهات أكثر من الارتداد إلى المتوسط.",
  Volatility: "حجم حركة السعر المعتادة خلال فترة. ينبغي أن تؤثر في حجم الصفقة، لأن اللوت الثابت يمثل مخاطرة مختلفة تمامًا في يوم هادئ مقارنة بيوم شديد التقلب.",
};

export function localizedCourse(course: Course, locale: "en" | "fr" | "ar"): CourseText {
  if (locale === "en") return course;
  return (locale === "fr" ? frCourses : arCourses)[course.slug] ?? course;
}

export function localizedPath(stage: LearningPathStage, index: number, locale: "en" | "fr" | "ar"): PathText {
  if (locale === "en") return stage;
  return (locale === "fr" ? frPath : arPath)[index] ?? stage;
}

export function localizedLevel(level: CourseLevel, locale: "en" | "fr" | "ar") {
  if (locale === "fr") return { beginner: "Débutant", intermediate: "Intermédiaire", advanced: "Avancé" }[level];
  if (locale === "ar") return { beginner: "مبتدئ", intermediate: "متوسط", advanced: "متقدم" }[level];
  return { beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced" }[level];
}

export function localizedGlossary(entry: GlossaryTerm, locale: "en" | "fr" | "ar") {
  if (locale === "en") return entry;
  const definition = (locale === "fr" ? frGlossary : arGlossary)[entry.term];
  return definition ? { ...entry, definition } : entry;
}
